# Generated by Django 6.1 on 2026-09-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
